# Problem 1

In [7]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.linspace(0,10,5)
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.shape)
# 4 - matris'i yeniden boyutlandırın
a.reshape(5,1)
# 5 - matris'in boyut sayısını öğrenin
a.ndim

[ 0.   2.5  5.   7.5 10. ]
(5,)


1

# Problem 2

In [13]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np
b = np.arange(1,10,2)
print(b)
# 2 - Oluşturduğunuz matrisi parçalayın
b1a, b1b = np.split(b,[2])
print(b1a,b1b)
# 3 - Parçalanmış matrisleri birleştirin
b1 = np.concatenate([b1a,b1b])
print(b1)
b == b1

[1 3 5 7 9]
[1 3] [5 7 9]
[1 3 5 7 9]


array([ True,  True,  True,  True,  True])

# Problem 3

In [22]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
b2a = np.arange(5,100,2)
b2 = np.random.choice(b2a, size=10, replace=False)
print(b2)
# 2 - matris'in özelliklerini inceleyin
print(b2.ndim)
print(b2.shape)
print(b2.size)
print(b2.dtype)

[33 63 75 53 27 91 11 45 19 59]
1
(10,)
10
int64
