# <center> Numpy

- faster math calculations
- Data Analysis
- scientific calculations
- like lists, but it is productive in the case of Data storage and vector operations

## Install

`pip install numpy`

## Update

`pip3 install --upgrade pip`

## Why we learn "numpy"? <br>
Here is the reason with a example


### Example 1
with classic method

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0,len(a)):
    ab.append(a[i] * b[i])

print(ab)

[2, 6, 12, 20]


with numpy

In [5]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a * b)

[ 2  6 12 20]


## .reshape()
- changing the shape of an array

In [6]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## .shape
- get the current shape of an array

In [7]:
print(multi.shape)

(3, 3)


In [8]:
print(x.shape)

(9,)


## .ndim
- represents the number of dimensions (axes) of the ndarray

In [9]:
print(x.ndim)

1


In [10]:
print(multi.ndim)

2


## Concatenation (Birleştirme)

### concatenate()
- add variables together

In [11]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [14]:
a =  np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


### axis
- Axes are defined for arrays with more than one dimension.
- the elements of axis 0 are rows (horizontal)
- the elements of axis 1 are columns (vertical)

In [16]:
print(np.concatenate([a,a], axis = 0))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [17]:
print(np.concatenate([a,a], axis = 1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## splitting (Array ayırma)

### split()
- Split an array into multiple sub-arrays of equal size.

In [19]:
m = np.array([1,2,3,99,99,4,5,6])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([4, 5, 6])]


In [20]:
a,b,c = np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[4 5 6]


### vsplit()
- Split an array into multiple sub-arrays vertically (row-wise)

In [24]:
n = np.arange(16).reshape(4,4)
print(np.vsplit(n,[2]))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


### hsplit()
- Split an array into multiple sub-arrays horizontally (column-wise).

In [25]:
print(np.hsplit(n,[2]))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


## Other Operators

### np.arange(start, stop, step)
- Return evenly spaced values within a given interval.

In [26]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### np.zeros()
- 

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### np.ones()

In [28]:
np.ones(4)

array([1., 1., 1., 1.])

## np.linspace()

In [29]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [31]:
np.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

In [32]:
np.random.randint(0,10,3)

array([6, 6, 6])

In [33]:
np.random.randint(2,22,5)

array([14,  5, 14,  9,  8])

In [35]:
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)
print((npMulti.sum(axis = 1))) # vertical sum
print((npMulti.sum(axis = 0))) # horizontal sum

[ 45 145 245 345 445]
[100 105 110 115 120 125 130 135 140 145]


## Numpy Features
- **ndim** : number of dimensions (boyut sayısı) 
- **shape** : size information (boyut bilgisi)
- **size** : total number of elements (toplam eleman sayısı)
- **dtype** : data type (veri tipi)

In [38]:
ex = np.random.randint(10, size = 10)
print(ex.ndim)
print(ex.shape)
print(ex.size)
print(ex.dtype)
print(ex)

1
(10,)
10
int64
[4 3 4 0 4 6 3 8 8 0]


## Sorting (Array Sıralama)

### sort()

In [40]:
s = np.array([2,3,4,67,87,98,58,89,1,3])
print(s)
s.sort()
print(s)

[ 2  3  4 67 87 98 58 89  1  3]
[ 1  2  3  3  4 58 67 87 89 98]


### normal()

In [41]:
s1 = np.random.normal(20,5,[3,3])
print(s1)

[[14.21791821 19.78986048 16.80564471]
 [23.68891436 32.88625854 16.49325257]
 [30.16251106 29.67106163 18.38972169]]


In [42]:
print(np.sort(s1, axis = 1))

[[14.21791821 16.80564471 19.78986048]
 [16.49325257 23.68891436 32.88625854]
 [18.38972169 29.67106163 30.16251106]]


In [43]:
print(np.sort(s1, axis = 0))

[[14.21791821 19.78986048 16.49325257]
 [23.68891436 29.67106163 16.80564471]
 [30.16251106 32.88625854 18.38972169]]


### index()


In [53]:
i = np.random.randint(10, size = 10)
print(i)
print(i[0])
print(i[-1])

[6 7 6 7 6 3 1 5 5 4]
6
4


In [54]:
print(i)
i[0] = 100
print(i)

[6 7 6 7 6 3 1 5 5 4]
[100   7   6   7   6   3   1   5   5   4]


In [58]:
x = np.random.randint(10, size = (3,5))
print(x)

[[6 0 2 4 4]
 [6 5 6 3 3]
 [4 5 7 7 4]]


In [59]:
print(x[0,0])

6


In [60]:
print(x[1,1])

5


In [61]:
x[1,1] = 7
print(x[1,1])
print(x)

7
[[6 0 2 4 4]
 [6 7 6 3 3]
 [4 5 7 7 4]]


In [62]:
x[1,1] = 3.14
print(x[1,1])
print(x)

3
[[6 0 2 4 4]
 [6 3 6 3 3]
 [4 5 7 7 4]]


## Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [63]:
a = np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [64]:
print(a[0:3])

[20 21 22]


In [65]:
print(a[:3])

[20 21 22]


In [67]:
print(a[3:])

[23 24 25 26 27 28 29]


In [69]:
print(a[1::2]) #ikişer ikişer artma

[21 23 25 27 29]


In [70]:
print(a[0::2]) #ikişer ikişer artma

[20 22 24 26 28]


In [71]:
print(a[2::2])

[22 24 26 28]


In [73]:
print(a[1::5])

[21 26]


In [75]:
s2 = np.random.randint(10, size = [5,5])
print(s2)

[[3 1 1 9 3]
 [2 5 4 3 8]
 [7 6 9 8 5]
 [2 4 6 6 1]
 [1 7 0 4 6]]


In [76]:
print(s2[:,0]) # sıfırıncı sütün

[3 2 7 2 1]


In [77]:
print(s2[:,1]) # brinci sütün

[1 5 6 4 7]


In [79]:
print(s2[0,:]) # sıfırncı satır

[3 1 1 9 3]


In [80]:
print(s2[1,:]) # birinci satır

[2 5 4 3 8]


In [81]:
print(s2[0:2,0:3]) # [sütünlar arası, satırlar arası]

[[3 1 1]
 [2 5 4]]


In [82]:
print(s2[::2,::2]) # (ikişer sütün atla, ikişer satır atla)

[[3 1 3]
 [7 9 5]
 [1 0 6]]


## Operate on subset (Alt Kümelerede işlem yapmak)

In [86]:
alt_s2 = s2[0:3,0:2]
alt_s2

array([[3, 1],
       [2, 5],
       [7, 6]])

In [88]:
alt_s2[0,0] = 100
alt_s2[1,1] = 200
print(alt_s2)

[[100   1]
 [  2 200]
 [  7   6]]


In [90]:
s2

array([[100,   1,   1,   9,   3],
       [  2, 200,   4,   3,   8],
       [  7,   6,   9,   8,   5],
       [  2,   4,   6,   6,   1],
       [  1,   7,   0,   4,   6]])

In [91]:
print(s2)

[[100   1   1   9   3]
 [  2 200   4   3   8]
 [  7   6   9   8   5]
 [  2   4   6   6   1]
 [  1   7   0   4   6]]


## Fancy Index
- In NumPy, fancy indexing allows us to use an array of indices to access multiple array elements at once. 

In [92]:
v = np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [94]:
ar = [1,3,5]
print(v[ar])
print(type(v))

[ 3  9 15]
<class 'numpy.ndarray'>


In [98]:
m = np.arange(9).reshape(3,3)
row = np.array([0,1])
column = np.array([1,2])
print(m)
print(m[row,column])
'''
    Yapılan işlem:
    İşlem 1: row 0 in column 1 (0,1)
    İşlem 2: row 1 in column 2 (1,2)
'''

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 5]


## Conditional Element Operations (Koşullu Eleman İşlemleri)

In [100]:
v = np.array([1,2,3,4,5])
print(v > 3)

[False False False  True  True]


In [101]:
print(v[v > 3])

[4 5]


In [102]:
print(v[v < 3])

[1 2]


In [103]:
print(v[v >= 3])

[3 4 5]


In [104]:
print(v[v <= 3])

[1 2 3]


In [106]:
print(v[v != 3])

[1 2 4 5]


In [107]:
print(v[v == 3])

[3]


## Mathematical Operations (Matematiksel İşlemler)

In [114]:
ma = np.array([1,2,3,4,5])
print(ma * 2) 

[ 2  4  6  8 10]


In [113]:
print(ma + 2)

[3 4 5 6 7]


In [116]:
print(ma * 5 / 10) 

[0.5 1.  1.5 2.  2.5]


In [117]:
print(ma ** 2)

[ 1  4  9 16 25]


In [118]:
print(np.subtract(v,3))

[-2 -1  0  1  2]


In [120]:
print(np.add(v,2))

[3 4 5 6 7]


In [121]:
print(np.multiply(v,5))

[ 5 10 15 20 25]


In [123]:
print(np.divide(v,2))

[0.5 1.  1.5 2.  2.5]


In [122]:
print(np.divide(v,10))

[0.1 0.2 0.3 0.4 0.5]


In [124]:
print(np.power(v,2))

[ 1  4  9 16 25]


In [125]:
print(np.mod(v,5))

[1 2 3 4 0]


In [126]:
print(np.absolute(v))

[1 2 3 4 5]


In [128]:
print(np.sin(v))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [130]:
print(np.log(10))

2.302585092994046


In [131]:
?np

Type:        module
String form: <module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/__init__.py'>
File:        /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snipp

## Solving Equation with Two Unknowns (İki Bilinmeyenli Denklem Çözümü)

In [133]:
# 5*x0 + x1 = 12
# x0 + 3*x1 = 10

a = np.array([[5,1],[1,3]])
b = np.array([12,10])
x = np.linalg.solve(a,b)
print(x) 

[1.85714286 2.71428571]
